#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Basquete")]
	public partial class JogoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertJogo(Jogo instance);
    partial void UpdateJogo(Jogo instance);
    partial void DeleteJogo(Jogo instance);
    partial void InsertTemporada(Temporada instance);
    partial void UpdateTemporada(Temporada instance);
    partial void DeleteTemporada(Temporada instance);
    #endregion
		
		public JogoDataContext() : 
				base(global::DAL.Properties.Settings.Default.BasqueteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JogoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JogoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JogoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JogoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Jogo> Jogo
		{
			get
			{
				return this.GetTable<Jogo>();
			}
		}
		
		public System.Data.Linq.Table<Temporada> Temporada
		{
			get
			{
				return this.GetTable<Temporada>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jogos")]
	public partial class Jogo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoJogo;
		
		private System.Nullable<int> _Pontuacao;
		
		private System.Nullable<int> _CodigoTemporada;
		
		private EntityRef<Temporada> _Temporada;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoJogoChanging(int value);
    partial void OnCodigoJogoChanged();
    partial void OnPontuacaoChanging(System.Nullable<int> value);
    partial void OnPontuacaoChanged();
    partial void OnCodigoTemporadaChanging(System.Nullable<int> value);
    partial void OnCodigoTemporadaChanged();
    #endregion
		
		public Jogo()
		{
			this._Temporada = default(EntityRef<Temporada>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_jogo", Storage="_CodigoJogo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoJogo
		{
			get
			{
				return this._CodigoJogo;
			}
			set
			{
				if ((this._CodigoJogo != value))
				{
					this.OnCodigoJogoChanging(value);
					this.SendPropertyChanging();
					this._CodigoJogo = value;
					this.SendPropertyChanged("CodigoJogo");
					this.OnCodigoJogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="pontuacao", Storage="_Pontuacao", DbType="Int")]
		public System.Nullable<int> Pontuacao
		{
			get
			{
				return this._Pontuacao;
			}
			set
			{
				if ((this._Pontuacao != value))
				{
					this.OnPontuacaoChanging(value);
					this.SendPropertyChanging();
					this._Pontuacao = value;
					this.SendPropertyChanged("Pontuacao");
					this.OnPontuacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_temporada", Storage="_CodigoTemporada", DbType="Int")]
		public System.Nullable<int> CodigoTemporada
		{
			get
			{
				return this._CodigoTemporada;
			}
			set
			{
				if ((this._CodigoTemporada != value))
				{
					this.OnCodigoTemporadaChanging(value);
					this.SendPropertyChanging();
					this._CodigoTemporada = value;
					this.SendPropertyChanged("CodigoTemporada");
					this.OnCodigoTemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="temporadas_jogos", Storage="_Temporada", ThisKey="CodigoTemporada", OtherKey="CodigoTemporada", IsForeignKey=true)]
		public Temporada Temporada
		{
			get
			{
				return this._Temporada.Entity;
			}
			set
			{
				Temporada previousValue = this._Temporada.Entity;
				if (((previousValue != value) 
							|| (this._Temporada.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Temporada.Entity = null;
						previousValue.Jogo.Remove(this);
					}
					this._Temporada.Entity = value;
					if ((value != null))
					{
						value.Jogo.Add(this);
						this._CodigoTemporada = value.CodigoTemporada;
					}
					else
					{
						this._CodigoTemporada = default(Nullable<int>);
					}
					this.SendPropertyChanged("Temporada");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.temporadas")]
	public partial class Temporada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoTemporada;
		
		private System.Nullable<System.DateTime> _Inicio;
		
		private System.Nullable<System.DateTime> _Fim;
		
		private EntitySet<Jogo> _Jogo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoTemporadaChanging(int value);
    partial void OnCodigoTemporadaChanged();
    partial void OnInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnInicioChanged();
    partial void OnFimChanging(System.Nullable<System.DateTime> value);
    partial void OnFimChanged();
    #endregion
		
		public Temporada()
		{
			this._Jogo = new EntitySet<Jogo>(new Action<Jogo>(this.attach_Jogo), new Action<Jogo>(this.detach_Jogo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_temporada", Storage="_CodigoTemporada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoTemporada
		{
			get
			{
				return this._CodigoTemporada;
			}
			set
			{
				if ((this._CodigoTemporada != value))
				{
					this.OnCodigoTemporadaChanging(value);
					this.SendPropertyChanging();
					this._CodigoTemporada = value;
					this.SendPropertyChanged("CodigoTemporada");
					this.OnCodigoTemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="inicio", Storage="_Inicio", DbType="Date")]
		public System.Nullable<System.DateTime> Inicio
		{
			get
			{
				return this._Inicio;
			}
			set
			{
				if ((this._Inicio != value))
				{
					this.OnInicioChanging(value);
					this.SendPropertyChanging();
					this._Inicio = value;
					this.SendPropertyChanged("Inicio");
					this.OnInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="fim", Storage="_Fim", DbType="Date")]
		public System.Nullable<System.DateTime> Fim
		{
			get
			{
				return this._Fim;
			}
			set
			{
				if ((this._Fim != value))
				{
					this.OnFimChanging(value);
					this.SendPropertyChanging();
					this._Fim = value;
					this.SendPropertyChanged("Fim");
					this.OnFimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="temporadas_jogos", Storage="_Jogo", ThisKey="CodigoTemporada", OtherKey="CodigoTemporada")]
		public EntitySet<Jogo> Jogo
		{
			get
			{
				return this._Jogo;
			}
			set
			{
				this._Jogo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Jogo(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Temporada = this;
		}
		
		private void detach_Jogo(Jogo entity)
		{
			this.SendPropertyChanging();
			entity.Temporada = null;
		}
	}
}
#pragma warning restore 1591
